import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import { CategoryAssignmentRule, CategoryAssignmentRulesState } from '../../types';

const initialState: CategoryAssignmentRulesState = {
  categoryAssignmentRules: [],
};

const categoryAssignmentRulesSlice = createSlice({
  name: 'categoryAssignmentRules',
  initialState,
  reducers: {
    addCategoryAssignmentRuleRedux(state, action: PayloadAction<CategoryAssignmentRule>) {
      state.categoryAssignmentRules.push(action.payload);
    },
    updateCategoryAssignmentRuleRedux(state, action: PayloadAction<CategoryAssignmentRule>) {
      const updatedCategoryAssignmentRule = action.payload;
      const index = state.categoryAssignmentRules.findIndex(
        ((rule: any) => rule.id === updatedCategoryAssignmentRule.id)
      );
      if (index !== -1) {
        state.categoryAssignmentRules[index] = updatedCategoryAssignmentRule;
      }
    },
    updateCategoryAssignmentRulePatternRedux(state, action: PayloadAction<{ id: string, pattern: string }>) {
      const { id, pattern } = action.payload;
      const index = state.categoryAssignmentRules.findIndex(
        ((rule: any) => rule.id === id)
      );
      if (index !== -1) {
        state.categoryAssignmentRules[index].pattern = pattern;
      }
    },
    updateCategoryAssignmentRuleCategoryIdRedux(state, action: PayloadAction<{ id: string, categoryId: string }>) {
      const { id, categoryId } = action.payload;
      const index = state.categoryAssignmentRules.findIndex(
        ((rule: any) => rule.id === id)
      );
      if (index !== -1) {
        state.categoryAssignmentRules[index].categoryId = categoryId;
      }
    },
    deleteCategoryAssignmentRuleRedux(state, action: PayloadAction<CategoryAssignmentRule>) {
      state.categoryAssignmentRules = state.categoryAssignmentRules.filter(
        ((rule: any) => rule.id !== action.payload.id)
      );
    },
    deleteCategoryAssignmentRuleByIdRedux(state, action: PayloadAction<string>) {
      state.categoryAssignmentRules = state.categoryAssignmentRules.filter(
        ((rule: any) => rule.id !== action.payload)
      );
    },
    addCategoryAssignmentRules(state, action: PayloadAction<CategoryAssignmentRule[]>) {
      state.categoryAssignmentRules = state.categoryAssignmentRules.concat(action.payload);
    },
    replaceCategoryAssignmentRulesRedux(state, action: PayloadAction<CategoryAssignmentRule[]>) {
      state.categoryAssignmentRules = action.payload;
    },
  },
});

// Export the actions generated by createSlice
export const {
  addCategoryAssignmentRuleRedux,
  updateCategoryAssignmentRuleRedux,
  updateCategoryAssignmentRulePatternRedux,
  updateCategoryAssignmentRuleCategoryIdRedux,
  deleteCategoryAssignmentRuleRedux,
  deleteCategoryAssignmentRuleByIdRedux,
  addCategoryAssignmentRules,
  replaceCategoryAssignmentRulesRedux,
} = categoryAssignmentRulesSlice.actions;

// Export the reducer to be included in the store
export default categoryAssignmentRulesSlice.reducer;